<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-08-28T22:25:44Z" name="Read data and Screenshot Suite" finished-at="2018-08-28T22:29:46Z" duration-ms="241781">
    <groups>
    </groups>
    <test started-at="2018-08-28T22:25:44Z" name="IE Test" finished-at="2018-08-28T22:29:46Z" duration-ms="241781">
      <class name="Com.HelloFresh.ScreenshotTest">
        <test-method signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:Com.HelloFresh.ScreenshotTest@54422e18]" started-at="2018-08-28T22:25:44Z" name="setUp" finished-at="2018-08-28T22:26:17Z" duration-ms="32720" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[IE]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://automationpractice.com/index.php]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="logInTest(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:Com.HelloFresh.ScreenshotTest@54422e18]" started-at="2018-08-28T22:26:17Z" name="logInTest" finished-at="2018-08-28T22:29:42Z" duration-ms="205717" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[MY ACCOUNT]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Welcome to your account.]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[controller=my-account]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[MY ACCOUNT]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: MY ACCOUNT
at org.testng.Assert.fail(Assert.java:96)
at Com.HelloFresh.ScreenshotTest.logInTest(ScreenshotTest.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:844)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInTest -->
        <test-method signature="LogOut()[pri:2, instance:Com.HelloFresh.ScreenshotTest@54422e18]" started-at="2018-08-28T22:29:42Z" name="LogOut" finished-at="2018-08-28T22:29:46Z" duration-ms="3295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogOut -->
      </class> <!-- Com.HelloFresh.ScreenshotTest -->
    </test> <!-- IE Test -->
  </suite> <!-- Read data and Screenshot Suite -->
</testng-results>
